<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-07 11:46

=======
# Generated by Django 5.2.4 on 2025-07-25 00:29

import accounts.models
>>>>>>> 9daefb6 (fix: add video embed support for post detail)
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=255)),
<<<<<<< HEAD
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/images/avatars/')),
=======
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_path)),
>>>>>>> 9daefb6 (fix: add video embed support for post detail)
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
