# Generated by Django 5.2 on 2025-05-12 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_counselorbooking_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='CounselorBooking',
        ),
    ]
